export enum WebSocketEvent {
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  RESOURCE_UPDATE = 'RESOURCE_UPDATE',
  CLAN_INVITE = 'CLAN_INVITE',
  CLAN_INVITE_ACCEPT = 'CLAN_INVITE_ACCEPT',
  GENERIC = 'GENERIC',
}
